<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;QA</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stripe.net" Version="43.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdTool.BusinessLogic\AdTool.BusinessLogic.csproj" />
    <ProjectReference Include="..\Configuration.cs\Configuration.csproj" />
  </ItemGroup>

</Project>
